# Build a LSIO compatible container for dev branches
name: Build & Publish Feature Container

# Run on any branch that isn't master or p3-dev
on:
    push:
        branches-ignore:
            - 'master'
            - 'python3-dev'

# Cancel previous run on this branch if a new push is made
concurrency:
    group: bpfc-${{ github.ref }}
    cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    push_to_registry:
        name: Build Docker image and push to GHCR
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write
        steps:
          - name: Checkout LSIO mylar3 repository (nightly)
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
            with:
              repository: 'linuxserver/docker-mylar3'
              ref: 'nightly'

          - name: Edit Dockerfile for current repo/branch
            run: |
              sed -i "s@mylar3/mylar3@${{github.repository}}@g" Dockerfile
              sed -i "s@commits/python3-dev@commits/${{github.ref_name}}@g" Dockerfile
              sed -i "/requirements.txt/a\ \ pip install --no-cache-dir --find-links https://wheel-index.linuxserver.io/ubuntu/ debugpy && \\\\" Dockerfile
              sed -i "/EXPOSE 8090/aEXPOSE 5678" Dockerfile
              sed -i "s@python3 /app/mylar3/Mylar.py@python3 -m debugpy --listen 0.0.0.0:5678 /app/mylar3/Mylar.py@g" ./root/etc/s6-overlay/s6-rc.d/svc-mylar3/run

          - name: Log in to the Container registry
            uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
            with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          - name: Build and push Docker image
            id: push
            uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}

          - name: Cleanup old untagged GHCR images
            uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
            with:
              keep-n-untagged: 5

