# Workflow for basic testing of pushes to development branches
name: Push to Feature Branches
permissions:
  actions: read
  contents: read
  deployments: write
  statuses: read

# Run on any branch that isn't master or a dev branch
on:
    push:
        branches-ignore:
            - 'master'
            - 'python3-dev'
            - '1000papercuts'

# Cancel previous run on this branch if a new push is made
concurrency:
    group: btb-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_and_test:
        if: ${{ github.repository != 'mylar3/mylar3' }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-22.04, windows-latest]
                python-version: ["3.8", "3.14"]        
        uses: ./.github/workflows/mylar_build_deploy_test.yml
        with:
          os: ${{ matrix.os }}
          py: ${{ matrix.python-version }}
          run_basic: true